Repository openshift-4-compliance/openshift-4-compliance-automation, pull requests merged in 2021-04, with the labels that each got.

#21 Added the "Disallow self provisioner ClusterRole" gatekeeper policy
  open-policy-agent/resource-exhaustion/disallow-self-provisioner/constraint.yaml
  open-policy-agent/resource-exhaustion/disallow-self-provisioner/template.yaml
Labels: enhancement, review

#25 Added a gatekeeper policy that verifies etcd encryption
  open-policy-agent/README.md
  open-policy-agent/etcd-security/verify-etcd-encryption/constraint.yaml
  open-policy-agent/etcd-security/verify-etcd-encryption/template.yaml
Labels: review

#28 Added policies to the OPA README.md
  open-policy-agent/README.md
Labels: documentation

#30 - Delete compliance Operator folder
  README.md
  compliance-operator/README.md
  compliance-operator/authentication-user-management/README.md
  compliance-operator/authorization/README.md
  compliance-operator/etcd-security/README.md
  compliance-operator/infrastructure-general/README.md
  compliance-operator/monitoring-observability/README.md
  compliance-operator/networking/README.md
  compliance-operator/resource-exhaustion/README.md
  compliance-operator/storage/README.md
  compliance-operator/trusted-image-sources/README.md
Labels: invalid, review

#31 Feature/add kyverno
  kyverno/README.md
  kyverno/authentication-user-management/README.md
  kyverno/authorization/README.md
  kyverno/etcd-security/README.md
  kyverno/infrastructure-general/README.md
  kyverno/monitoring-observability/README.md
  kyverno/networking/README.md
  kyverno/resource-exhaustion/README.md
  kyverno/storage/README.md
  kyverno/trusted-image-sources/README.md
Labels: enhancement, review

#32 - Kyverno policy protect-default-scc
  kyverno/README.md
  kyverno/authentication-user-management/protect-default-scc.yaml
Labels: review

#34 Added https only route policy
  kyverno/README.md
  kyverno/networking/httpsonly.yaml
Labels: Kyverno, enhancement, review

#37 Added the disallow-self-provisioner.yaml Policy for Kyverno
  kyverno/README.md
  kyverno/resource-exhaustion/disallow-self-provisioner.yaml
Labels: Kyverno, enhancement, new-policy

#36 Adding hostipc policy for new scc
  kyverno/README.md
  kyverno/authorization/host-namespaces/README.md
  kyverno/authorization/host-namespaces/disallow-host-ipc.yaml
Labels: Kyverno, review

#39 Disallow HostPID access
  kyverno/README.md
  kyverno/authorization/host-namespaces/disallow-host-pid.yaml
Labels: review

#40 Disallow Host network for PODs and custom-scc
  kyverno/README.md
  kyverno/authorization/host-namespaces/disallow-host-network.yaml
Labels: review

#41 Disallow Host ports for PODs and custom-scc
  kyverno/README.md
  kyverno/authorization/host-namespaces/disallow-host-ports.yaml
Labels: review

#43 Etcdbackup
  redhat-acm/README.md
  redhat-acm/etcd-security/policy-etcd-backup.yaml
Labels: review

#44 Kustomization integration for Advanced Cluster Management policies
  redhat-acm/kustomization.yaml
Labels: enhancement
