Repository openshift-4-compliance/openshift-4-compliance-automation, pull requests merged in 2021-06, with the labels that each got.

#73 OAuth secured identityProviders only
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/README.md
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/constraint.yaml
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/template.yaml
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/test/approved.yaml
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/test/non-approved-1.yaml
  open-policy-agent/authentication-user-management/oauth-secured-identity-providers-only/test/non-approved-2.yaml
Labels: review

#87 Change enforcementAction to dryrun in Gatekeeper policies
  open-policy-agent/authentication-user-management/shorten-tokens/constraint.yaml
  open-policy-agent/authorization/disallow-privileged-scc-usage/constraint.yaml
  open-policy-agent/authorization/prevent-default-serviceaccount-usage/constraint.yaml
  open-policy-agent/etcd-security/verify-etcd-encryption/constraint.yaml
  open-policy-agent/networking/block-nodeport-services/constraint.yaml
  open-policy-agent/networking/external-ips/constraint.yaml
  open-policy-agent/networking/httpsonly/constraint.yaml
  open-policy-agent/resource-exhaustion/disallow-self-provisioner/constraint.yaml
  open-policy-agent/trusted-image-sources/disallowedtags/constraint.yaml
Labels: bugfix, enhancement

#88 Change remediationAction to inform in RHACM policies
  redhat-acm/authentication-user-management/gatekeeper-shorten-tokens/gatekeeper-shorten-tokens.yaml
  redhat-acm/authorization/gatekeeper-disalllow-privileged-scc-usage/gatekeeper-disalllow-privileged-scc-usage.yaml
  redhat-acm/authorization/gatekeeper-prevent-default-serviceaccount-usage/gatekeeper-prevent-default-serviceaccount-usage.yaml
  redhat-acm/networking/allow-port-from-namespace-networkpolicy-policy/allow-port-from-namespace-networkpolicy-policy.yaml
  redhat-acm/networking/gatekeeper-allow-httpsonly/gatekeeper-allow-httpsonly.yaml
  redhat-acm/networking/gatekeeper-disallow-external-ip-services/gatekeeper-disallow-external-ip-services.yaml
  redhat-acm/networking/gatekeeper-disallow-nodeport/gatekeeper-disallow-nodeport.yaml
  redhat-acm/resource-exhaustion/gatekeeper-disallow-self-provisioner-policy/gatekeeper-disallow-self-provisioner-policy.yaml
  redhat-acm/resource-exhaustion/limitrange-policy/limitrange-policy.yaml
  redhat-acm/trusted-image-sources/gatekeeper-disallow-image-tags/gatekeeper-disallow-image-tags.yaml
Labels: bugfix

#81 Gatekeeper oauth secured identity providers only acm
  redhat-acm/README.md
  redhat-acm/authentication-user-management/gatekeeper-oauth-secured-identity-providers-only/README.md
  redhat-acm/authentication-user-management/gatekeeper-oauth-secured-identity-providers-only/gatekeeper-oauth-secured-identity-providers-only.yaml
Labels: review

#92 Fixing broken links in the readme
  open-policy-agent/README.md
  redhat-acm/README.md
Labels: bugfix

#96 Added ResourceQuota policy for RHACM
  redhat-acm/README.md
  redhat-acm/kustomization.yaml
  redhat-acm/resource-exhaustion/resourcequota-policy/README.md
  redhat-acm/resource-exhaustion/resourcequota-policy/resourcequota-policy.yaml
Labels: new-policy

#100 Disallow host namespaces using Gatekeeper
  open-policy-agent/README.md
  open-policy-agent/authorization/disallow-host-namespaces/constraint.yaml
  open-policy-agent/authorization/disallow-host-namespaces/template.yaml
  open-policy-agent/kustomization.yaml
Labels: new-policy

#94 Fixed RHACM policy to monitor all default SCC instead of the restricted SCC only
  redhat-acm/README.md
  redhat-acm/authorization/default-scc-validation-policy/README.md
  redhat-acm/authorization/default-scc-validation-policy/default-scc-validation-policy.yaml
  redhat-acm/authorization/restricted-scc-validation-policy/restricted-scc-validation-policy.yaml
  redhat-acm/kustomization.yaml
Labels: bugfix

#69 Serviceaccount automounttoken prevention
  open-policy-agent/README.md
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/README.md
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/constraint.yaml
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/template.yaml
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/test/service_account_should_not_work_advanced.yaml
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/test/service_account_should_not_work_basic.yaml
  open-policy-agent/authorization/serviceaccount_automounttoken_prevention/test/service_account_should_work.yaml
Labels: review
