Repository openshift-4-compliance/openshift-4-compliance-automation, pull requests merged in 2021-05, with the labels that each got.

#45 Added ADR to the repository
  ADR.md
Labels: enhancement

#46 Added shorten token lifespan policy for Red Hat Advanced Cluster Management
  redhat-acm/README.md
  redhat-acm/authentication-user-management/gatekeeper-shorten-tokens.yaml
  redhat-acm/kustomization.yaml
Labels: new-policy, review

#47 Changed file format
  redhat-acm/README.md
  redhat-acm/authentication-user-management/group-policy.yaml
  redhat-acm/authentication-user-management/kubeadmin-policy.yaml
  redhat-acm/authorization/disallowed-role-policy.yaml
  redhat-acm/authorization/gatekeeper-disalllow-priv-scc.yaml
  redhat-acm/authorization/restricted-scc-validation-policy.yaml
  redhat-acm/authorization/role-binding-policy.yaml
  redhat-acm/authorization/role-policy.yaml
  redhat-acm/etcd-security/etcdencryption-policy.yaml
  redhat-acm/kustomization.yaml
  redhat-acm/networking/allow-port-from-namespace-networkpolicy-policy.yaml
  redhat-acm/networking/deny-all-networkpolicy-policy.yaml
  redhat-acm/networking/gatekeeper-allow-httpsonly.yaml
  redhat-acm/networking/gatekeeper-disallow-external-ip-services.yaml
  redhat-acm/networking/gatekeeper-disallow-nodeport.yaml
  redhat-acm/resource-exhaustion/disallow-self-provisioner-policy.yaml
  redhat-acm/resource-exhaustion/limitrange-policy.yaml
  redhat-acm/trusted-image-sources/gatekeeper-disallow-image-tags.yaml
Labels: bugfix

#48 Added Gatekeeper operator policy
  redhat-acm/README.md
  redhat-acm/infrastructure-general/gatekeeper-operator-policy.yaml
  redhat-acm/kustomization.yaml
Labels: enhancement, new-policy

#53 Changed the etcd backup policy file format to fit standard
  redhat-acm/README.md
  redhat-acm/etcd-security/etcdbackup-policy.yaml
Labels: enhancement

#51 Fixed disallow-privileged-scc-usage Gatekeeper policy
  open-policy-agent/README.md
  open-policy-agent/authorization/README.md
  open-policy-agent/authorization/disallow-privileged-scc-usage/README.md
  open-policy-agent/authorization/disallow-privileged-scc-usage/constraint.yaml
  open-policy-agent/authorization/disallow-privileged-scc-usage/template.yaml
Labels: bugfix

#55 fix links
  redhat-acm/README.md
Labels: bugfix

#52 Fixed the disallow-privileged-scc-usage.yaml policy for Red Hat Advanced Cluster Management
  redhat-acm/README.md
  redhat-acm/authorization/README.md
  redhat-acm/authorization/gatekeeper-disalllow-privileged-scc-usage/README.md
  redhat-acm/authorization/gatekeeper-disalllow-privileged-scc-usage/gatekeeper-disalllow-privileged-scc-usage.yaml
  redhat-acm/kustomization.yaml
Labels: bugfix

#61 prevent 'default' serviceaccount usage
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/README.md
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/constraint.yaml
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/template.yaml
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/test/approved_pod.yaml
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/test/not_approved_pod_1.yaml
  open-policy-agent/authorization/prevent_default_serviceaccount_usage/test/test_deployment_not_approved.yaml
Labels: review

#42 Deny RunAsAny for custom scc
  kyverno/README.md
  kyverno/authorization/disallow-scc-runasany.yaml
Labels: review

#85 Fixed self-provisioner policy for RHACM
  redhat-acm/README.md
  redhat-acm/kustomization.yaml
  redhat-acm/resource-exhaustion/disallow-self-provisioner-policy/README.md
  redhat-acm/resource-exhaustion/disallow-self-provisioner-policy/disallow-self-provisioner-policy.yaml
  redhat-acm/resource-exhaustion/gatekeeper-disallow-self-provisioner-policy/README.md
  redhat-acm/resource-exhaustion/gatekeeper-disallow-self-provisioner-policy/gatekeeper-disallow-self-provisioner-policy.yaml
Labels: bugfix
