Repository openshift-4-compliance/openshift-4-compliance-automation, pull requests merged in 2021-03, with the labels that each got.

#1 Added initial RHACM policies
  README.md
  open-policy-agent/networking/httpsonly/constraint.yml
  open-policy-agent/networking/httpsonly/template.yml
  redhat-acm/authentication-user-management/kubeadmin-policy.yml
  redhat-acm/authorization/disallowed-role-policy.yml
  redhat-acm/authorization/group-policy.yml
  redhat-acm/authorization/role-binding-policy.yml
  redhat-acm/authorization/role-policy.yml
  redhat-acm/etcd-security/etcdencryption-policy.yml
  redhat-acm/networking/allow-port-from-namespace-networkpolicy-policy.yml
  redhat-acm/networking/deny-all-networkpolicy-policy.yml
  redhat-acm/networking/gatekeeper-allow-httpdonly.yml
  redhat-acm/resource-exhaustion/disallow-self-provisioner-policy.yml
  redhat-acm/resource-exhaustion/limitrange-policy.yml
Labels: review

#2 Adding two OPA rules
  open-policy-agent/networking/block-nodeport-services/constraint.yaml
  open-policy-agent/networking/block-nodeport-services/template.yaml
  open-policy-agent/networking/external-ips/constraint.yaml
  open-policy-agent/networking/external-ips/template.yaml
Labels: review

#5 Added no-privilege-scc gatekeeper policy
  open-policy-agent/authorization/no-priv-scc/constraint.yaml
  open-policy-agent/authorization/no-priv-scc/template.yaml
Labels: enhancement, review

#4 add deleted kubeadmin rule
  open-policy-agent/authentication-user-management/delete-kubeadmin/constraint.yaml
  open-policy-agent/authentication-user-management/delete-kubeadmin/template.yaml
Labels: enhancement

#7 block tag latest for images
  open-policy-agent/trusted-image-sources/disallowedtags/constraint.yaml
  open-policy-agent/trusted-image-sources/disallowedtags/template.yaml
Labels: enhancement, review

#8 Added a public visible compliance doc reference
  README.md
Labels: documentation, review

#11 Disallow Node Port and External IP policies using RHACM
  redhat-acm/networking/gatekeeper-allow-httpsonly.yml
  redhat-acm/networking/gatekeeper-disallow-external-ip-services.yml
  redhat-acm/networking/gatekeeper-disallow-nodeport.yml
Labels: enhancement, review

#12 Update constraint.yaml
  open-policy-agent/networking/external-ips/constraint.yaml
Labels: bugfix

#18 modify disallowed tags name
  open-policy-agent/trusted-image-sources/disallowedtags/constraint.yaml
Labels: bugfix

#19 Added the Resource Exhaustion section in the RHACM doc
  redhat-acm/README.md
Labels: documentation, review

#22 Added Restricted SCC validation policy for RHACM
  redhat-acm/authorization/restricted-scc-validation-policy.yml
Labels: enhancement, review

#23 README for OPA Gatekeeper
  open-policy-agent/README.md
Labels: documentation, review

#24 Added a gatekeeper policy that controls the expiration time of oauth tokens
  open-policy-agent/authentication-user-management/shorten-tokens/constraint.yaml
  open-policy-agent/authentication-user-management/shorten-tokens/template.yaml
Labels: enhancement, review
